// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processor_processor,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.157250,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=294,HLS_SYN_LUT=580,HLS_VERSION=2024_2}" *)

module processor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pc_in,
        main_memory_out,
        main_memory_out_ap_vld,
        opcode_out,
        opcode_out_ap_vld,
        op_value_1_out,
        op_value_1_out_ap_vld,
        op_value_2_out,
        op_value_2_out_ap_vld,
        result_out,
        result_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] pc_in;
output  [31:0] main_memory_out;
output   main_memory_out_ap_vld;
output  [31:0] opcode_out;
output   opcode_out_ap_vld;
output  [31:0] op_value_1_out;
output   op_value_1_out_ap_vld;
output  [31:0] op_value_2_out;
output   op_value_2_out_ap_vld;
output  [31:0] result_out;
output   result_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg main_memory_out_ap_vld;
reg opcode_out_ap_vld;
reg op_value_1_out_ap_vld;
reg op_value_2_out_ap_vld;
reg result_out_ap_vld;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] main_memory_2_q0;
wire   [31:0] main_memory_2_q1;
wire   [31:0] register_file_1_q0;
wire   [31:0] register_file_1_q1;
reg   [31:0] pc_in_read_reg_533;
wire   [0:0] icmp_ln52_fu_308_p2;
reg   [0:0] icmp_ln52_reg_538;
wire    ap_CS_fsm_state2;
wire   [3:0] field_4_fu_318_p1;
reg   [3:0] field_4_reg_547;
wire    ap_CS_fsm_state3;
reg   [3:0] field_1_reg_553;
reg   [3:0] address_reg_558;
reg   [11:0] imm12_reg_563;
wire   [0:0] or_ln65_fu_374_p2;
reg   [0:0] or_ln65_reg_568;
wire   [10:0] opcode_fu_394_p3;
reg   [10:0] opcode_reg_576;
reg   [3:0] field_3_reg_580;
wire    ap_CS_fsm_state4;
wire   [3:0] field_5_fu_432_p3;
reg   [3:0] field_5_reg_596;
wire    ap_CS_fsm_state5;
wire   [3:0] address_1_fu_448_p3;
reg   [3:0] address_1_reg_603;
wire   [31:0] result_5_fu_475_p2;
wire   [31:0] result_4_fu_481_p2;
wire   [31:0] result_3_fu_487_p2;
wire   [31:0] result_2_fu_493_p2;
wire   [31:0] result_1_fu_499_p2;
wire   [31:0] result_fu_505_p2;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [31:0] ap_phi_mux_result_6_phi_fu_258_p18;
reg   [31:0] result_6_reg_254;
reg    ap_predicate_pred156_state5;
reg    ap_predicate_pred161_state6;
reg    ap_predicate_pred167_state5;
reg    ap_predicate_pred172_state5;
reg    ap_predicate_pred177_state5;
reg    ap_predicate_pred182_state5;
reg    ap_predicate_pred187_state5;
reg    ap_predicate_pred192_state5;
reg    ap_predicate_pred210_state5;
reg   [31:0] ap_phi_mux_storemerge6_phi_fu_287_p6;
reg   [31:0] storemerge6_reg_284;
wire    ap_CS_fsm_state9;
reg    ap_predicate_pred232_state6;
wire   [63:0] zext_ln55_fu_314_p1;
wire   [63:0] zext_ln84_fu_423_p1;
wire   [63:0] zext_ln85_fu_428_p1;
wire   [63:0] zext_ln121_fu_460_p1;
wire   [63:0] zext_ln118_1_fu_470_p1;
reg    ap_predicate_pred161_state5;
wire   [63:0] zext_ln118_fu_511_p1;
wire   [63:0] zext_ln135_fu_519_p1;
reg    ap_predicate_pred156_state6;
wire   [63:0] zext_ln138_fu_524_p1;
wire   [63:0] zext_ln132_fu_529_p1;
reg    main_memory_2_ce1_local;
reg   [3:0] main_memory_2_address1_local;
reg    main_memory_2_ce0_local;
reg   [3:0] main_memory_2_address0_local;
reg    main_memory_2_we1_local;
reg    main_memory_2_we0_local;
reg    register_file_1_we1_local;
reg    register_file_1_ce1_local;
reg   [3:0] register_file_1_address1_local;
reg    register_file_1_we0_local;
reg   [31:0] register_file_1_d0_local;
reg    register_file_1_ce0_local;
reg   [3:0] register_file_1_address0_local;
wire   [28:0] tmp_fu_298_p4;
wire   [9:0] trunc_ln_fu_322_p4;
wire   [0:0] icmp_ln65_fu_362_p2;
wire   [0:0] icmp_ln65_1_fu_368_p2;
wire   [10:0] trunc_ln_cast_fu_380_p1;
wire   [10:0] tmp_1_fu_384_p4;
wire   [3:0] field_1_1_fu_417_p3;
wire   [11:0] imm12_1_fu_438_p3;
wire   [3:0] add_ln121_fu_454_p2;
wire   [3:0] add_ln118_fu_465_p2;
wire   [31:0] imm12_1_cast_fu_444_p1;
wire   [3:0] add_ln135_fu_515_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

processor_main_memory_2_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
main_memory_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(main_memory_2_address0_local),
    .ce0(main_memory_2_ce0_local),
    .we0(main_memory_2_we0_local),
    .d0(ap_phi_mux_result_6_phi_fu_258_p18),
    .q0(main_memory_2_q0),
    .address1(main_memory_2_address1_local),
    .ce1(main_memory_2_ce1_local),
    .we1(main_memory_2_we1_local),
    .d1(register_file_1_q0),
    .q1(main_memory_2_q1)
);

processor_register_file_1_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
register_file_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(register_file_1_address0_local),
    .ce0(register_file_1_ce0_local),
    .we0(register_file_1_we0_local),
    .d0(register_file_1_d0_local),
    .q0(register_file_1_q0),
    .address1(register_file_1_address1_local),
    .ce1(register_file_1_ce1_local),
    .we1(register_file_1_we1_local),
    .d1(main_memory_2_q1),
    .q1(register_file_1_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred192_state5 == 1'b1))) begin
        result_6_reg_254 <= result_fu_505_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred187_state5 == 1'b1))) begin
        result_6_reg_254 <= result_1_fu_499_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred182_state5 == 1'b1))) begin
        result_6_reg_254 <= result_2_fu_493_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred177_state5 == 1'b1))) begin
        result_6_reg_254 <= result_3_fu_487_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred172_state5 == 1'b1))) begin
        result_6_reg_254 <= result_4_fu_481_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred167_state5 == 1'b1))) begin
        result_6_reg_254 <= result_5_fu_475_p2;
    end else if ((((ap_predicate_pred210_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred156_state5 == 1'b1)))) begin
        result_6_reg_254 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storemerge6_reg_284 <= main_memory_2_q0;
    end else if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        storemerge6_reg_284 <= ap_phi_mux_result_6_phi_fu_258_p18;
    end else if (((opcode_reg_576 == 11'd1986) & (icmp_ln52_reg_538 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        storemerge6_reg_284 <= register_file_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        address_1_reg_603 <= address_1_fu_448_p3;
        ap_predicate_pred156_state6 <= (opcode_reg_576 == 11'd1984);
        ap_predicate_pred161_state6 <= (opcode_reg_576 == 11'd1986);
        ap_predicate_pred232_state6 <= ((opcode_reg_576 == 11'd1112) | ((opcode_reg_576 == 11'd1624) | ((opcode_reg_576 == 11'd1104) | ((opcode_reg_576 == 11'd1360) | ((opcode_reg_576 == 11'd580) | ((opcode_reg_576 == 11'd836) | (~(opcode_reg_576 == 11'd1986) & ~(opcode_reg_576 == 11'd1984))))))));
        field_5_reg_596 <= field_5_fu_432_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        address_reg_558 <= {{main_memory_2_q0[15:12]}};
        field_1_reg_553 <= {{main_memory_2_q0[19:16]}};
        field_3_reg_580 <= {{main_memory_2_q0[8:5]}};
        field_4_reg_547 <= field_4_fu_318_p1;
        imm12_reg_563 <= {{main_memory_2_q0[21:10]}};
        opcode_reg_576 <= opcode_fu_394_p3;
        or_ln65_reg_568 <= or_ln65_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_predicate_pred156_state5 <= (opcode_reg_576 == 11'd1984);
        ap_predicate_pred161_state5 <= (opcode_reg_576 == 11'd1986);
        ap_predicate_pred167_state5 <= (opcode_reg_576 == 11'd836);
        ap_predicate_pred172_state5 <= (opcode_reg_576 == 11'd580);
        ap_predicate_pred177_state5 <= (opcode_reg_576 == 11'd1360);
        ap_predicate_pred182_state5 <= (opcode_reg_576 == 11'd1104);
        ap_predicate_pred187_state5 <= (opcode_reg_576 == 11'd1624);
        ap_predicate_pred192_state5 <= (opcode_reg_576 == 11'd1112);
        ap_predicate_pred210_state5 <= (~(opcode_reg_576 == 11'd1112) & ~(opcode_reg_576 == 11'd1624) & ~(opcode_reg_576 == 11'd1104) & ~(opcode_reg_576 == 11'd1360) & ~(opcode_reg_576 == 11'd580) & ~(opcode_reg_576 == 11'd836) & ~(opcode_reg_576 == 11'd1986) & ~(opcode_reg_576 == 11'd1984));
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln52_reg_538 <= icmp_ln52_fu_308_p2;
        pc_in_read_reg_533 <= pc_in;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1))) begin
        ap_phi_mux_result_6_phi_fu_258_p18 = 32'd0;
    end else begin
        ap_phi_mux_result_6_phi_fu_258_p18 = result_6_reg_254;
    end
end

always @ (*) begin
    if (((opcode_reg_576 == 11'd1986) & (icmp_ln52_reg_538 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_phi_mux_storemerge6_phi_fu_287_p6 = register_file_1_q1;
    end else begin
        ap_phi_mux_storemerge6_phi_fu_287_p6 = storemerge6_reg_284;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        main_memory_2_address0_local = zext_ln138_fu_524_p1;
    end else if (((ap_predicate_pred156_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        main_memory_2_address0_local = zext_ln135_fu_519_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        main_memory_2_address0_local = zext_ln55_fu_314_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        main_memory_2_address0_local = 4'd15;
    end else begin
        main_memory_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_pred161_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        main_memory_2_address1_local = zext_ln118_1_fu_470_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred156_state5 == 1'b1))) begin
        main_memory_2_address1_local = zext_ln121_fu_460_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        main_memory_2_address1_local = 4'd14;
    end else begin
        main_memory_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_predicate_pred156_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        main_memory_2_ce0_local = 1'b1;
    end else begin
        main_memory_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred161_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred156_state5 == 1'b1)))) begin
        main_memory_2_ce1_local = 1'b1;
    end else begin
        main_memory_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        main_memory_2_we0_local = 1'b1;
    end else begin
        main_memory_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (ap_predicate_pred156_state5 == 1'b1))) begin
        main_memory_2_we1_local = 1'b1;
    end else begin
        main_memory_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        main_memory_out_ap_vld = 1'b1;
    end else begin
        main_memory_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        op_value_1_out_ap_vld = 1'b1;
    end else begin
        op_value_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        op_value_2_out_ap_vld = 1'b1;
    end else begin
        op_value_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        opcode_out_ap_vld = 1'b1;
    end else begin
        opcode_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        register_file_1_address0_local = zext_ln138_fu_524_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1))) begin
        register_file_1_address0_local = zext_ln118_fu_511_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        register_file_1_address0_local = zext_ln85_fu_428_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        register_file_1_address0_local = 4'd15;
    end else begin
        register_file_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        register_file_1_address1_local = zext_ln132_fu_529_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        register_file_1_address1_local = zext_ln84_fu_423_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        register_file_1_address1_local = 4'd14;
    end else begin
        register_file_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | ((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1)))) begin
        register_file_1_ce0_local = 1'b1;
    end else begin
        register_file_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4))) begin
        register_file_1_ce1_local = 1'b1;
    end else begin
        register_file_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        register_file_1_d0_local = ap_phi_mux_result_6_phi_fu_258_p18;
    end else if (((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1))) begin
        register_file_1_d0_local = main_memory_2_q1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        register_file_1_d0_local = main_memory_2_q0;
    end else begin
        register_file_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1)))) begin
        register_file_1_we0_local = 1'b1;
    end else begin
        register_file_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        register_file_1_we1_local = 1'b1;
    end else begin
        register_file_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_reg_538 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        result_out_ap_vld = 1'b1;
    end else begin
        result_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln52_fu_308_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln52_fu_308_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((ap_predicate_pred232_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state6) & (ap_predicate_pred161_state6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_465_p2 = (address_1_fu_448_p3 + field_3_reg_580);

assign add_ln121_fu_454_p2 = (address_1_fu_448_p3 + field_5_fu_432_p3);

assign add_ln135_fu_515_p2 = (address_1_reg_603 + field_5_reg_596);

assign address_1_fu_448_p3 = ((or_ln65_reg_568[0:0] == 1'b1) ? 4'd0 : address_reg_558);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign field_1_1_fu_417_p3 = ((or_ln65_reg_568[0:0] == 1'b1) ? 4'd0 : field_1_reg_553);

assign field_4_fu_318_p1 = main_memory_2_q0[3:0];

assign field_5_fu_432_p3 = ((or_ln65_reg_568[0:0] == 1'b1) ? 4'd0 : field_4_reg_547);

assign icmp_ln52_fu_308_p2 = (($signed(tmp_fu_298_p4) < $signed(29'd1)) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_368_p2 = ((trunc_ln_fu_322_p4 == 10'd836) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_362_p2 = ((trunc_ln_fu_322_p4 == 10'd580) ? 1'b1 : 1'b0);

assign imm12_1_cast_fu_444_p1 = imm12_1_fu_438_p3;

assign imm12_1_fu_438_p3 = ((or_ln65_reg_568[0:0] == 1'b1) ? imm12_reg_563 : 12'd0);

assign main_memory_out = main_memory_2_q0;

assign op_value_1_out = register_file_1_q1;

assign op_value_2_out = register_file_1_q0;

assign opcode_fu_394_p3 = ((or_ln65_fu_374_p2[0:0] == 1'b1) ? trunc_ln_cast_fu_380_p1 : tmp_1_fu_384_p4);

assign opcode_out = opcode_fu_394_p3;

assign or_ln65_fu_374_p2 = (icmp_ln65_fu_362_p2 | icmp_ln65_1_fu_368_p2);

assign result_1_fu_499_p2 = (register_file_1_q0 - register_file_1_q1);

assign result_2_fu_493_p2 = (register_file_1_q1 & register_file_1_q0);

assign result_3_fu_487_p2 = (register_file_1_q1 | register_file_1_q0);

assign result_4_fu_481_p2 = (register_file_1_q0 + imm12_1_cast_fu_444_p1);

assign result_5_fu_475_p2 = (register_file_1_q0 - imm12_1_cast_fu_444_p1);

assign result_fu_505_p2 = (register_file_1_q0 + register_file_1_q1);

assign result_out = ap_phi_mux_storemerge6_phi_fu_287_p6;

assign tmp_1_fu_384_p4 = {{main_memory_2_q0[31:21]}};

assign tmp_fu_298_p4 = {{pc_in[31:3]}};

assign trunc_ln_cast_fu_380_p1 = trunc_ln_fu_322_p4;

assign trunc_ln_fu_322_p4 = {{main_memory_2_q0[31:22]}};

assign zext_ln118_1_fu_470_p1 = add_ln118_fu_465_p2;

assign zext_ln118_fu_511_p1 = field_5_reg_596;

assign zext_ln121_fu_460_p1 = add_ln121_fu_454_p2;

assign zext_ln132_fu_529_p1 = field_5_reg_596;

assign zext_ln135_fu_519_p1 = add_ln135_fu_515_p2;

assign zext_ln138_fu_524_p1 = field_4_reg_547;

assign zext_ln55_fu_314_p1 = pc_in_read_reg_533;

assign zext_ln84_fu_423_p1 = field_1_1_fu_417_p3;

assign zext_ln85_fu_428_p1 = field_3_reg_580;

endmodule //processor
